Sec area xfmr
PNNL-CIM-Tools/CIM-Graph pull request #13
Opened 2023-04-28 04:32 UTC by AAndersn

Remove boundary devices from lower level areas:
* remove secondary transformers from secondary area
* remove switches from switch switch area

2023-04-28 20:18 UTC, afisher1 requested changes
@AAndersn There was a change in the sparql query in switch_phase.py that I think isn't right. I left a comment at the line in question.

2023-04-28 20:18 UTC, afisher1 commented on cimgraph/loaders/sparql/rc4_2021/switch_phase.py
> +        OPTIONAL {?eq cim:SwitchPhase.phaseSide1 ?phs2.
shouldn't this be phaseSide2?

2023-05-01 20:03 UTC, afisher1 commented
@AAnderson I don't see any code changes in this PR that would perform the removal of boundary devices from the lower level areas and testing my app with these changes confirms that boundary devices are still being located in lower level areas.

2023-05-01 20:10 UTC, afisher1 commented on cimgraph/loaders/sparql/rc4_2021/switch_phase.py
> +        OPTIONAL {?eq cim:SwitchPhase.phaseSide1 ?phs2.
After talking with @AAndersn it should be phaseSide2 and has been resolved

2023-05-01 20:12 UTC, afisher1 requested changes
@AAndersn looking at all the code changes I see nothing in here that would cause the removal of boundary devices from existing in the lower level distributed areas. Testing with the distributed ybus service still shows the transformer is still showing up in the secondary area for the ieee13nodeckt.

2023-05-01 21:03 UTC, AAndersn commented
Andy, there seems to be something wrong with git on my server. There should be a commit with changes to SecondaryArea.py and SwitchArea py. My history shows it was pushed but I can't find it on GitHub

2023-05-02 18:10 UTC, afisher1 commented
@AAndersn , I just checked the history on those files on sec_area_xfmr branch. The last commits for cimgraph/models/switch_area.py and cimgraph/models/secondary_area.py were on February 4. So somehow your changes didn't get pushed from your local repo somehow. if you still having issues with git, can you try emailing me the files?

2023-05-03 18:29 UTC, afisher1 approved these changes
This has all typo fixes and boundary device issues present and working as expected.

2023-05-08 19:17 UTC, merged

2023-05-08 19:45 UTC, craig8 commented
Fixed #11