Feature/68
PNNL-CIM-Tools/CIM-Graph pull request #80
Opened 2024-11-23 01:54 UTC by AAndersn

2024-11-23 01:55 UTC, AAndersn commented
Addresses issues 68 through 79

2024-11-23 02:15 UTC, AAndersn commented
fix #56

2024-11-23 02:30 UTC, AAndersn commented
fixes #37 as well

2024-12-03 18:37 UTC, afisher1 requested changes
I am requesting changes to address a couple bugs. cimhub_2023.py line 35:
current: if self.mRID is not None:
change: if self.mRID is not None and str(self.identifier) != self.mRID:

cimhub_2023.py lines 100-106 need to be outside of the if statement on line 96

2024-12-03 22:17 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +            if self.mRID is not None:
```

2024-12-03 22:58 UTC, afisher1 requested changes

2024-12-03 22:58 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +        if mRID is not None and str(self.identifier) != self.mRID:
```suggestion
        if mRID is not None:
            if str(self.identifier) != mRID:
                # Handle inconsistent capitalization / underscores
                if mRID.strip('_') != mRID:
                    self.__uuid__.mrid_has_underscore = True
                    if uri is None:
                        self.__uuid__.uri_has_underscore = True
                if mRID.lower() != mRID:
                    self.__uuid__.mrid_is_capitalized = True
                    if uri is None:
                        self.__uuid__.uri_is_capitalized = True
                try:
                    self.identifier = UUID(mRID.strip('_').lower())
                    invalid_mrid = False
                except:
                    seed = seed + mRID
                    _log.warning(f'mRID {mRID} not a valid UUID, generating new UUID')
            else:
                invalid_mrid = False
            if 'mRID' in self.__dataclass_fields__:
                self.mRID = mRID
```

2024-12-03 22:58 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +    def __post_init__(self) -> None:
As I see it there are a couple reasons to call self.uuid() in post_init.

1. self.identifier is None.
2. self.identifer doesn't match self.mRID.

Currently if the dataclass instance has self.mRID it calls self.uuid() no matter what. This call is completely unnecessary if a user specified identifier and mRID such that they match and the is the source of the bug I'm seeing where identifier if different from what I specified in the constructor.

2024-12-03 23:16 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +    def __post_init__(self) -> None:
```suggestion
    def __post_init__(self) -> None:
        if self.identifier is None:
            if 'mRID' in self.__dataclass_fields__:
                if self.mRID is not None:
                    self.uuid(mRID = self.mRID)
                else:
                    self.uuid()
            else:
                self.uuid()
        else:
            if 'mRID' in self.__dataclass_fields__:
                if str(self.identifier) != self.mRID:
                    if self.mRID is not None:
                        self.uuid(mRID = self.mRID)
                    else:
                        self.mRID = str(self.identifier)
```

2024-12-03 23:22 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +        if mRID is not None and str(self.identifier) != self.mRID:
The suggested change in here fixes an issue where the user/post_init calls uuid(mRID=) such that mRID = str(identifier) and invalid_mrid never gets set to False thus triggering another UUID generation and overwrites self.identifier.

2024-12-04 20:43 UTC, afisher1 requested changes

2024-12-04 20:43 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +                        self.mRID = str(self.identifier)
```suggestion
                        self.uuid(mRID=str(self.identifier))
```

2024-12-04 20:43 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +            try:
```suggestion
            if str(self.identifier) != uri:
                try:
                    self.__uuid__.uuid = UUID(uri.strip('_').lower())
                    self.identifier = self.__uuid__.uuid
                    invalid_mrid = False
                except:
                    seed = seed + uri
                    _log.warning(f'URI {uri} not a valid UUID, generating new UUID')
            else:
                self.__uuid__.uuid = self.identifier
                invalid_mrid = False
```

2024-12-04 20:43 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +            if str(self.identifier) != mRID:
```suggestion
            # Handle inconsistent capitalization / underscores
            if mRID.strip('_') != mRID:
                self.__uuid__.mrid_has_underscore = True
                if uri is None:
                    self.__uuid__.uri_has_underscore = True
            if mRID.lower() != mRID:
                self.__uuid__.mrid_is_capitalized = True
                if uri is None:
                    self.__uuid__.uri_is_capitalized = True
            if str(self.identifier) != mRID:
                try:
                    self.__uuid__.uuid = UUID(mRID.strip('_').lower())
                    self.identifier = self.__uuid__.uuid
                    invalid_mrid = False
                except:
                    seed = seed + mRID
                    _log.warning(f'mRID {mRID} not a valid UUID, generating new UUID')
            else:
                self.__uuid__.uuid = self.identifier
                invalid_mrid = False
            if 'mRID' in self.__dataclass_fields__:
                self.mRID = mRID
```

2024-12-04 20:43 UTC, afisher1 commented on cimgraph/data_profile/cimhub_2023/cimhub_2023.py
> +            if name is not None:
```suggestion
            if not self.identifier:
                if name is not None:
                    seed = seed + f'{self.__class__.__name__}:{name}'
                    randomGenerator = Random(seed)
                    self.__uuid__.uuid = UUID(int=randomGenerator.getrandbits(128), version=4)
                    self.name = name
                else:
                    self.__uuid__.uuid = uuid4()
                self.identifier = self.__uuid__.uuid
                # Write mRID string for backwards compatibility
                if 'mRID' in self.__dataclass_fields__:
                    if mRID is not None:
                        self.mRID = mRID
                    else:
                        self.mRID = str(self.identifier)
            else:
                self.__uuid__.uuid = self.identifier 
                # Write mRID string for backwards compatibility
                if 'mRID' in self.__dataclass_fields__:
                    if mRID is not None:
                        self.mRID = mRID
                    else:
                        self.mRID = str(self.identifier)
```

2024-12-06 01:12 UTC, AAndersn commented
fixes #82

2024-12-06 01:13 UTC, AAndersn commented
fixes #79

2024-12-11 23:17 UTC, afisher1 approved these changes

2024-12-11 23:19 UTC, merged